version: "2.0"
services:
  titra:
    image: kromit/titra
    container_name: titra
    depends_on:
      - mongodb
    environment:
      - ROOT_URL=${ROOT_URL}
      - MONGO_URL=mongodb://mongodb/titra
      - PORT=3002
    ports:
      - "3002:3002"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
    volumes:
     - /root/mongodb:/data/db
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    command: --cleanup --schedule "0 0 0 * * *" --label-enable
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
