version: "2.0"
services:
  titra:
    image: kromit/titra
    container_name: titra
    depends_on:
      - mongodb
    environment:
      - ROOT_URL=${ROOT_URL}
      - MONGO_URL=mongodb://mongodb/titra
      - PORT=3002
    ports:
      - "3002:3002"
    restart: always
  mongodb:
    image: mongo:4.2
    container_name: mongodb
    restart: always
